### ISSUE TITLE
Rename Out.to() to Out.out()

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#2760]
with the migration away from stage names as methods on Aggregation, this old name doesn't make any semantic sense.

Provide a rewrite recipe for migrations

**Comment by timtebeek** [comment]
If the method rename is all there is to it, then this could be as simple as adding
`rewrite/src/main/resources/META-INF/rewrite/morphia3.yml` with
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: dev.morphia.UpgradetoMorphia3
displayName: Upgrade to Morphia 3
description: Adopt new dependencies and breaking changes in moving to Morphia 3.
recipeList:
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: dev.morphia.aggregation.stages.Out to(..)
      newMethodName: out
      matchOverrides: "True"
      ignoreDefinition: "False"
```
I've composed this one quickly through the builder at https://app.moderne.io/recipes/builder
You can similarly add onto the `recipeList` to for instance [upgrade Gradle or Maven dependency versions](https://app.moderne.io/recipes/org.openrewrite.java.dependencies.UpgradeDependencyVersion).
